# --- Main Colors ---
background            #19120d
foreground            #f0dfd6
cursor                #f0dfd6
cursor_text_color     #19120d

selection_background  #5b412f
selection_foreground  #ffdcc5

url_color             #c7ca95

# --- ANSI Colors ---
color0                #19120d
color1                #ffb4ab
color2                #c7ca95
color3                #e4bfa7
color4                #ffb782
color5                #c7ca95
color6                #e4bfa7
color7                #f0dfd6

color8                #52443b
color9                #93000a
color10               #464920
color11               #5b412f
color12               #6d390a
color13               #5b412f
color14               #464920
color15               #d6c3b7

# --- Starship Prompt Bubbles ---
color255              #6d390a
color254              #ffb782
color253              #5b412f
color252              #e4bfa7
color251              #464920
color250              #c7ca95
color249              #93000a
color248              #ffb4ab

color232              #ffdcc5
color233              #4f2500
color234              #ffdcc5
color235              #422b1a
color236              #e3e6af
color237              #30330b
color238              #ffdad6
color239              #690005
color240              #ffdcc5

# Matched with unthemed light/dark
color243              #ffb782
color244              #ffb4ab
color245              #52443b

# --- UI Elements ---
active_tab_foreground   #4f2500
active_tab_background   #ffb782
inactive_tab_foreground #ffdcc5
inactive_tab_background #6d390a

active_border_color     #ffb782
inactive_border_color   #9f8d83

# --- Marks ---
mark1_foreground        #301400
mark1_background        #ffdcc5
mark2_foreground        #2a1708
mark2_background        #ffdcc5
mark3_foreground        #1b1d00
mark3_background        #e3e6af
