source-file ~/.config/tmux/theme.conf
# Set background to dark blue and foreground text to white
# set -g status-style bg="#0088dd",fg="#ffffff"

# Set prefix to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix


setw -g mode-keys vi

# Set true color support
set -ga terminal-overrides ",xterm-256color*:Tc"
set-option -g default-terminal "xterm-256color"

set-option -g set-clipboard on

# Enable mouse mode
set -g mouse on


bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel


# Set a longer history limit
set -g history-limit 10000

# -----------------------------------------------------------------------------
# THEME (Tokyonight)
# -----------------------------------------------------------------------------

# Reload config with r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Sourced ~/.config/tmux/tmux.conf"

# Split panes with | and -
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# Create new window with c
bind c new-window -c "#{pane_current_path}"

# Pane navigation with hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane navigation with Alt + hjkl
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Window navigation
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Synchronize panes
bind x setw synchronize-panes

# Create a new session
bind C command-prompt -p "New Session:" "new-session -s '%%'"

# Launch default shell as a non-login shell
set -g default-command "${SHELL}"

# update-environment
set -g update-environment 'HOME ZDOTDIR KDE_SESSION_VERSION KDE_FULL_SESSION DESKTOP_SESSION DBUS_SESSION_BUS_ADDRESS SESSION_MANAGER DISPLAY WAYLAND_DISPLAY SSH_AUTH_SOCK'
