# Set background to dark blue and foreground text to white
# set -g status-style bg="#0088dd",fg="#ffffff"

setw -g mode-keys vi

# Set true color support
set -ga terminal-overrides ",xterm-256color*:Tc"
set-option -g default-terminal "xterm-256color"

set-option -g set-clipboard on

# Enable mouse mode
set -g mouse on


bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel


# Set a longer history limit
set -g history-limit 10000

# -----------------------------------------------------------------------------
# THEME (Tokyonight)
# -----------------------------------------------------------------------------
source-file ~/.config/tmux/theme.conf
